CREATE DATABASE IF NOT EXISTS carsalesdb;
USE carsalesdb;
CREATE TABLE Cars (
    Car_ID VARCHAR(10) PRIMARY KEY,
    Brand VARCHAR(50) NOT NULL,
    Model VARCHAR(50) NOT NULL,
    Year INT CHECK (Year >= 2000),
    Color VARCHAR(30),
    Engine_Type ENUM('Petrol','Diesel','Electric','Hybrid') NOT NULL,
    Transmission ENUM('Automatic','Manual') NOT NULL,
    Price DECIMAL(10,2) NOT NULL CHECK (Price > 0),
    Quantity_In_Stock INT NOT NULL CHECK (Quantity_In_Stock >= 0),
    Status ENUM('Available','Sold','Reserved') DEFAULT 'Available'
);
CREATE TABLE Customers (
    Customer_ID VARCHAR(10) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Gender ENUM('Male','Female') NOT NULL,
    Age INT CHECK (Age > 0 AND Age < 120),
    Phone VARCHAR(30),
    Email VARCHAR(100),
    City VARCHAR(100)
);
CREATE TABLE Sales (
    Sale_ID VARCHAR(10) PRIMARY KEY,
    Customer_ID VARCHAR(10) NOT NULL,
    Car_ID VARCHAR(10) NOT NULL,cars
    Sale_Date DATE,
    Quantity INT CHECK (Quantity > 0),
    Sale_Price DECIMAL(10,2) CHECK (Sale_Price > 0),
    Payment_Method ENUM('Cash','Credit','Installment') NOT NULL,
    Salesperson VARCHAR(100),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID),
    FOREIGN KEY (Car_ID) REFERENCES Cars(Car_ID)
);

SELECT * FROM CARS 
WHERE PRICE > 50000 AND STATUS="AVAILABLE" ORDER BY PRICE DESC;

SELECT NAME,PHONE FROM CUSTOMERS 
WHERE AGE > 30 AND CITY LIKE'NEW%';
SELECT C.NAME,S.SALE_DATE ,S.SALESPERSON FROM SALES AS S
JOIN CUSTOMERS AS C ON C.CUSTOMER_ID = S.CUSTOMER_ID;
SELECT BRAND ,MODEL,PRICE FROM CARS
WHERE TRANSMISSION='AUTOMATIC' AND ENGINE_TYPE='PETROL';
SELECT DISTINCT C.CITY FROM CUSTOMERS AS C
JOIN SALES AS S ON C.CUSTOMER_ID = S.CUSTOMER_ID;
SELECT Brand , SUM(PRICE) AS TOTAL_REVENUE FROM CARS
group by BRAND
ORDER BY TOTAL_REVENUE DESC ;
SELECT BRAND, COUNT(*) AS COUNT_SOLD FROM CARS 
GROUP BY BRAND ORDER BY COUNT_SOLD  DESC;
SELECT ENGINE_TYPE , AVG(PRICE) FROM CARS
GROUP BY ENGINE_TYPE;
SELECT SALESPERSON, SUM(SALE_PRICE) FROM SALES
WHERE COUNT(SALESPERSON) > 3 GROUP BY SALESPERSON ;
SELECT SALESPERSON,
COUNT(*) AS total_sales
FROM SALES
GROUP BY SALESPERSON
HAVING COUNT(*) > 3;
SELECT NAME ,COUNT(QUANTITY_IN_STOCK) AS QUNANTITY_CARS FROM CARS
JOIN CUSTOMERS ON CUSTOMER_ID=CUSTOMER_ID
GROUP BY NAME ORDER BY QUNANTITY_CARS DESC;
SELECT BRAND,SUM(SALE_PRICE) AS TOTAL_SALES FROM SALES
JOIN CARS ON SALES.CAR_ID = CARS.CAR_ID GROUP BY BRAND HAVING TOTAL_SALES > 20000;

SELECT CUSTOMER_ID,COUNT(*) AS TOTAL_CAR FROM SALES
GROUP BY CUSTOMER_ID HAVING COUNT(*) > 2;
SELECT SALESPERSON, SUM(QUANTITY) AS COUNT_SALES FROM SALES
WHERE YEAR(SALE_DATE) = 2025 GROUP BY SALESPERSON HAVING SUM(QUANTITY) > 5;


SELECT BRAND,SUM(STATUS) AS TOTAL_SOLD FROM CARS
WHERE STATUS = 'SOLD' GROUP BY BRAND HAVING TOTAL_SOLD > 10;

SELECT BRAND ,AVG(PRICE) AS AVERAGE_CAR_PRICE FROM CARS
GROUP BY BRAND HAVING AVERAGE_CAR_PRICE > 60000;

SELECT * FROM CARS 
LEFT JOIN SALES ON CARS.CAR_ID = SALES.CAR_ID; 

SELECT * FROM SALES 
RIGHT JOIN CUSTOMERS ON SALES.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID;
SELECT * FROM CARS;
SELECT * FROM SALES;
SELECT * FROM CUSTOMERS;
 SELECT 
    s.SALE_DATE,
    s.CUSTOMER_ID,
    c.CAR_ID,
    c.BRAND,
    c.MODEL,
    s.QUANTITY
FROM SALES s
INNER JOIN CARs c
    ON s.CAR_ID = c.CAR_ID
WHERE YEAR(s.SALE_DATE) = 2025
  AND s.QUANTITY > 2;


select city ,avg(sale_price) from customers
join sales on sales.customer_id=customers.customer_id
group by city order by avg(sale_price) desc;